spring:

weather:
  api:
    api-key: ${WEATHER_API_KEY}  # This reads from .env
    timeout: 30s
  cache:
    ttl:5m

# Logging (if needed)
logging:
  level:
    root: INFO
    com.yashaswi.weatherapi: DEBUG
    org.springframework.web: DEBUG
